#!/usr/bin/env python3
"""
Generate a single markdown file embedding the source tree for quick snapshotting.

Usage:
  python tools/generate_tracefincontext.py --output docs/trace-invest/tracefincontext.md

Defaults: output file above, excludes `tests`, `docs`, `.git`, `node_modules`, `__pycache__`, `.venv`.

The script writes a header and then for each included file writes a section:

### File: <path>
```<lang>
<content>
```

It skips files larger than 1MB by default to avoid huge binary blobs.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Iterable, List
import mimetypes
import sys


DEFAULT_EXCLUDES = {"tests", "docs", ".git", "node_modules", "__pycache__", ".venv", "venv"}
TEXT_EXTS = {
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".json",
    ".yaml",
    ".yml",
    ".ini",
    ".cfg",
    ".md",
    ".txt",
    ".html",
    ".css",
}


def is_text_file(path: Path) -> bool:
    if path.suffix.lower() in TEXT_EXTS:
        return True
    type_, _ = mimetypes.guess_type(str(path))
    if type_ and type_.startswith("text"):
        return True
    try:
        with path.open("rb") as f:
            chunk = f.read(2048)
            if b"\0" in chunk:
                return False
    except Exception:
        return False
    return True


def iter_source_files(root: Path, excludes: List[str]) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        parts = set(Path(dirpath).parts)
        if parts & set(excludes):
            # skip traversing this subtree
            dirnames[:] = []
            continue

        for fn in sorted(filenames):
            p = Path(dirpath) / fn
            # skip large files
            try:
                if p.stat().st_size > 1_000_000:  # 1 MB
                    continue
            except Exception:
                continue

            if any(ex in str(p).split(os.sep) for ex in excludes):
                continue

            # include typical source file types or readable text
            if is_text_file(p):
                yield p


def lang_from_suffix(path: Path) -> str:
    s = path.suffix.lower()
    return {
        ".py": "python",
        ".ts": "typescript",
        ".tsx": "tsx",
        ".js": "javascript",
        ".jsx": "jsx",
        ".json": "json",
        ".md": "markdown",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".html": "html",
        ".css": "css",
        ".ini": "ini",
    }.get(s, "text")


def generate(root: Path, out: Path, excludes: List[str]) -> int:
    out.parent.mkdir(parents=True, exist_ok=True)
    files = list(iter_source_files(root, excludes))

    with out.open("w", encoding="utf-8") as f:
        f.write("# tracefincontext snapshot\n\n")
        f.write(f"Generated by generate_tracefincontext.py at root: {root}\n\n")
        f.write("---\n\n")

        f.write("## File tree (selected source files)\n\n")
        for p in files:
            rel = p.relative_to(root)
            f.write(f"- {rel}\n")

        f.write("\n---\n\n")

        for p in files:
            rel = p.relative_to(root)
            f.write(f"### File: {rel}\n")
            lang = lang_from_suffix(p)
            f.write(f"```{lang}\n")
            try:
                text = p.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                try:
                    text = p.read_text(encoding="latin-1")
                except Exception:
                    text = "<could not decode file>"
            except Exception as exc:
                text = f"<error reading file: {exc}>"
            f.write(text.rstrip() + "\n")
            f.write("```\n\n")

    return len(files)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repository root to scan")
    parser.add_argument("--output", default="docs/trace-invest/tracefincontext.md", help="Output markdown file")
    parser.add_argument(
        "--exclude",
        action="append",
        help="Path segment to exclude (can be repeated). Defaults: tests, docs, .git, node_modules, __pycache__",
    )
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    out = Path(args.output).resolve()

    excludes = set(DEFAULT_EXCLUDES)
    if args.exclude:
        excludes.update(args.exclude)

    print(f"Scanning root: {root}")
    print(f"Excluding: {sorted(excludes)}")
    print(f"Writing to: {out}")

    count = generate(root, out, list(excludes))
    print(f"Wrote {count} files into {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
